version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-xe:21.3.0
    environment:
      ORACLE_PASSWORD: Admin@123
      # Oracle user: SYSTEM (SYS)
      # Service name: XEPDB1
      APP_USER: my_user
      APP_USER_PASSWORD: User@123
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle_data:
